

                     SUMMARY OF  PM7 CALCULATION

                                                       MOPAC v22.1.0 Linux
                                                       Sun Mar 24 00:57:15 2024

           Empirical Formula: C9 H14 N2 O3  =    28 atoms

 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -60.17145 KCAL/MOL =    -251.75735 KJ/MOL
          DIELECTRIC ENERGY       =         -0.71709 EV
          GRADIENT NORM           =          2.20353          =       0.41643 PER ATOM
          DIPOLE                  =          6.77740 DEBYE   POINT GROUP:  C1  
          NO. OF FILLED LEVELS    =         39
          IONIZATION POTENTIAL    =          9.972523 EV
          HOMO LUMO ENERGIES (EV) =         -9.973 -0.580
          MOLECULAR WEIGHT        =        198.2212
          COSMO AREA              =        267.55 SQUARE ANGSTROMS
          COSMO VOLUME            =        264.23 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    22    H     2    11.62139
            H    19    O     4     6.38366
            H     8    H    11     2.79626
          SCF CALCULATIONS        =         19
          WALL-CLOCK TIME         =      1.002 SECONDS
          COMPUTATION TIME        =     26.161 SECONDS


          FINAL GEOMETRY OBTAINED
* ===============================
* Input file for Mopac
* ===============================
 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit
  C    -0.10188786 +1   0.05189613 +1   0.14133956 +1
  H    -1.14385700 +1   0.17402466 +1   0.44525224 +1
  N    -0.22719960 +1  -2.37866765 +1   0.18198910 +1
  O    -1.41803622 +1  -2.57110148 +1   0.35819673 +1
  O     0.62529405 +1  -3.12395795 +1   0.64517364 +1
  H     1.87774985 +1   0.85951334 +1   0.10186599 +1
  C     0.20304821 +1  -1.20609217 +1  -0.61091962 +1
  H    -0.34017386 +1  -1.21506302 +1  -1.59620877 +1
  H     1.29163227 +1  -1.30062443 +1  -0.86765603 +1
  C     0.83768358 +1   0.96210160 +1   0.38844041 +1
  H     0.64113712 +1   1.89565023 +1   0.90080625 +1
  C     6.53960038 +1  -2.73916260 +1   0.25284944 +1
  C     7.91655715 +1  -2.73221744 +1  -0.02147940 +1
  C     8.52901141 +1  -1.50219095 +1  -0.27684910 +1
  C     7.76530900 +1  -0.33871763 +1  -0.24514661 +1
  C     6.40014681 +1  -0.43313018 +1   0.05046298 +1
  N     5.79890081 +1  -1.61513423 +1   0.28781189 +1
  H     5.99751865 +1  -3.67465429 +1   0.44713546 +1
  H     8.21705065 +1   0.63147848 +1  -0.44864098 +1
  H     5.76067432 +1   0.45736560 +1   0.09948624 +1
  C     8.68107246 +1  -4.00248929 +1  -0.06314610 +1
  H     9.74894466 +1  -3.86665234 +1   0.16885378 +1
  H     8.63195742 +1  -4.46016017 +1  -1.06673350 +1
  H     8.29856244 +1  -4.75427720 +1   0.64447480 +1
  H     9.59757606 +1  -1.45500648 +1  -0.50036763 +1
  H     2.51963826 +1  -2.99355064 +1  -0.23080898 +1
  O     3.17164245 +1  -2.66950897 +1  -0.85692980 +1
  H     3.88517974 +1  -2.30810923 +1  -0.31178738 +1

