

                     SUMMARY OF  PM7 CALCULATION

                                                       MOPAC v22.1.0 Linux
                                                       Sun Mar 24 01:49:30 2024

           Empirical Formula: C10 H16 N2 O3  =    31 atoms

 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -65.79532 KCAL/MOL =    -275.28761 KJ/MOL
          DIELECTRIC ENERGY       =         -0.85454 EV
          GRADIENT NORM           =          4.33314          =       0.77826 PER ATOM
          DIPOLE                  =         10.75785 DEBYE   POINT GROUP:  C1  
          NO. OF FILLED LEVELS    =         42
          IONIZATION POTENTIAL    =          9.923784 EV
          HOMO LUMO ENERGIES (EV) =         -9.924 -0.469
          MOLECULAR WEIGHT        =        212.2480
          COSMO AREA              =        290.66 SQUARE ANGSTROMS
          COSMO VOLUME            =        290.88 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    28    O     4    12.52809
            H    24    H    11     7.14084
            H     9    H    27     2.72308
          SCF CALCULATIONS        =         29
          WALL-CLOCK TIME         =      2.663 SECONDS
          COMPUTATION TIME        =          2 MINUTES AND 0.252 SECONDS


          FINAL GEOMETRY OBTAINED
* ===============================
* Input file for Mopac
* ===============================
 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit
  C    -1.15221175 +1  -0.24102669 +1   0.10911884 +1
  H    -2.24064442 +1  -0.16735043 +1   0.17506166 +1
  N    -1.55110534 +1  -2.63050301 +1   0.62326591 +1
  O    -2.71940474 +1  -2.35622374 +1   0.84324544 +1
  O    -1.17063064 +1  -3.78668097 +1   0.51242269 +1
  H     0.68154024 +1   0.75281512 +1  -0.36610667 +1
  C    -0.54992033 +1  -1.55128821 +1   0.50603662 +1
  H     0.24953955 +1  -1.87382515 +1  -0.21399617 +1
  H    -0.03152931 +1  -1.45812852 +1   1.50521751 +1
  C    -0.39721349 +1   0.78056561 +1  -0.28981494 +1
  H    -0.80483606 +1   1.74149152 +1  -0.57422468 +1
  C     5.75176427 +1  -2.96092256 +1   0.89319812 +1
  C     7.08124471 +1  -3.13201091 +1   0.48530244 +1
  C     7.75400812 +1  -2.02611839 +1  -0.05889770 +1
  C     7.03926425 +1  -0.83944464 +1  -0.24740773 +1
  C     5.69889884 +1  -0.77334735 +1   0.14353473 +1
  N     5.06813977 +1  -1.81228582 +1   0.72458779 +1
  H     5.20487809 +1  -3.78098903 +1   1.38105369 +1
  H     7.51744154 +1   0.03154770 +1  -0.69443582 +1
  H     5.10074053 +1   0.13600872 +1  -0.00082238 +1
  C     7.69066753 +1  -4.47863460 +1   0.61943637 +1
  H     8.78848504 +1  -4.45942236 +1   0.66665990 +1
  H     7.42232835 +1  -5.11410360 +1  -0.24368726 +1
  H     7.34395919 +1  -5.01016700 +1   1.51987698 +1
  C     9.19776985 +1  -2.08971213 +1  -0.40057279 +1
  H     9.59716888 +1  -1.13632726 +1  -0.77738288 +1
  H     9.41421419 +1  -2.85166241 +1  -1.16719388 +1
  H     9.80352783 +1  -2.35721937 +1   0.48369038 +1
  H     3.15839071 +1  -3.25724918 +1   0.91453621 +1
  O     2.91309419 +1  -3.70762724 +1   0.09565414 +1
  H     3.48266275 +1  -3.29511326 +1  -0.56449323 +1

