

                     SUMMARY OF  PM7 CALCULATION

                                                       MOPAC v22.1.0 Linux
                                                       Sun Mar 24 13:25:01 2024

           Empirical Formula: C9 H14 N2 O3  =    28 atoms

 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -58.19966 KCAL/MOL =    -243.50737 KJ/MOL
          DIELECTRIC ENERGY       =         -0.67034 EV
          GRADIENT NORM           =         10.51878          =       1.98786 PER ATOM
          DIPOLE                  =          7.47548 DEBYE   POINT GROUP:  C1  
          NO. OF FILLED LEVELS    =         39
          IONIZATION POTENTIAL    =          9.984835 EV
          HOMO LUMO ENERGIES (EV) =         -9.985 -0.529
          MOLECULAR WEIGHT        =        198.2212
          COSMO AREA              =        270.07 SQUARE ANGSTROMS
          COSMO VOLUME            =        265.47 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    25    O     4    11.27501
            H    23    H    11     7.15783
            H    22    H     8     3.45867
          SCF CALCULATIONS        =         45
          WALL-CLOCK TIME         =      1.734 SECONDS
          COMPUTATION TIME        =          2 MINUTES AND 22.089 SECONDS


          FINAL GEOMETRY OBTAINED
* ===============================
* Input file for Mopac
* ===============================
 PM7 CHARGE=0 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit
  C    -0.09469549 +1   0.05083661 +1   0.14687296 +1
  H    -1.13457511 +1   0.17382899 +1   0.45813829 +1
  N    -0.21261255 +1  -2.38060310 +1   0.19692575 +1
  O    -1.40562560 +1  -2.58716120 +1   0.37369230 +1
  O     0.64780710 +1  -3.10349716 +1   0.67094464 +1
  H     1.88140933 +1   0.87039274 +1   0.09849193 +1
  C     0.20134948 +1  -1.20906555 +1  -0.60576080 +1
  H    -0.35028181 +1  -1.22429361 +1  -1.58059530 +1
  H     1.28607753 +1  -1.30291494 +1  -0.87182270 +1
  C     0.84261853 +1   0.96401142 +1   0.39212231 +1
  H     0.64213239 +1   1.89518921 +1   0.90821738 +1
  C     6.49087514 +1  -2.42178910 +1  -0.07659684 +1
  C     7.83362455 +1  -2.74079092 +1   0.17732419 +1
  C     8.79231301 +1  -1.74145560 +1  -0.00641144 +1
  C     8.38960379 +1  -0.47810531 +1  -0.43359041 +1
  C     7.02964865 +1  -0.24281721 +1  -0.65954196 +1
  N     6.10063993 +1  -1.20548235 +1  -0.49381245 +1
  H     5.69763281 +1  -3.17186639 +1   0.04998323 +1
  H     9.11640984 +1   0.31968436 +1  -0.57982935 +1
  H     6.66043350 +1   0.73500414 +1  -0.99489307 +1
  C     8.19164617 +1  -4.11391202 +1   0.61250405 +1
  H     9.09133943 +1  -4.14178726 +1   1.24778002 +1
  H     8.39546097 +1  -4.76105187 +1  -0.25183098 +1
  H     7.38411308 +1  -4.59795913 +1   1.18705587 +1
  H     9.84952884 +1  -1.95002897 +1   0.16997500 +1
  H     3.24457063 +1  -1.99062699 +1  -0.52857615 +1
  O     3.37808146 +1  -1.52609481 +1  -1.36206717 +1
  H     4.28748824 +1  -1.19111043 +1  -1.27935959 +1

