

                     SUMMARY OF  PM7 CALCULATION

                                                       MOPAC v22.1.0 Linux
                                                       Sun Mar 24 12:03:23 2024

           Empirical Formula: C8 H10 N3 O8  =    29 atoms

 PM7 CHARGE=-1 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =       -215.53913 KCAL/MOL =    -901.81574 KJ/MOL
          DIELECTRIC ENERGY       =         -4.80735 EV
          GRADIENT NORM           =          7.94751          =       1.47582 PER ATOM
          DIPOLE                  =         29.48890 DEBYE   POINT GROUP:  C1  
          NO. OF FILLED LEVELS    =         53
          CHARGE ON SYSTEM        =         -1
          IONIZATION POTENTIAL    =         10.269905 EV
          HOMO LUMO ENERGIES (EV) =        -10.270 -1.939
          MOLECULAR WEIGHT        =        276.1823
          COSMO AREA              =        295.40 SQUARE ANGSTROMS
          COSMO VOLUME            =        299.51 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            O    22    O    11    10.77391
            O    25    H    16     7.70653
            O    21    H    23     5.08245
          SCF CALCULATIONS        =         21
          WALL-CLOCK TIME         =      1.070 SECONDS
          COMPUTATION TIME        =          1 MINUTE AND 31.990 SECONDS


          FINAL GEOMETRY OBTAINED
* ===============================
* Input file for Mopac
* ===============================
 PM7 CHARGE=-1 SINGLET AUX DUMP=30M ITRY=15000 eps=78.4 T=14D PL THREADS=40

 Mopac file generated by Gabedit
  C    -0.77463226 +1   1.15981160 +1  -0.03181025 +1
  C     0.57960284 +1   1.17833687 +1   0.32138806 +1
  C     1.31750324 +1  -0.01022470 +1   0.30630121 +1
  C     0.69149775 +1  -1.20409247 +1  -0.04862851 +1
  C    -0.67106578 +1  -1.20107129 +1  -0.38371842 +1
  C    -1.42389056 +1  -0.02537107 +1  -0.38727556 +1
  H     1.05197646 +1   2.13249982 +1   0.60762099 +1
  H     1.24661570 +1  -2.15507795 +1  -0.06566691 +1
  H    -2.49400586 +1  -0.02996222 +1  -0.65583044 +1
  N    -1.31122666 +1  -2.45023314 +1  -0.73645048 +1
  O    -2.49481817 +1  -2.44517146 +1  -1.04223755 +1
  O    -0.64787207 +1  -3.47722420 +1  -0.71843386 +1
  C     2.77023518 +1   0.04018837 +1   0.70776365 +1
  H     2.84762887 +1   0.52252479 +1   1.73199250 +1
  C     3.49426877 +1  -1.29825511 +1   0.74479542 +1
  H     4.55145008 +1  -1.18729984 +1   1.04584304 +1
  H     3.50459339 +1  -1.80824824 +1  -0.23039817 +1
  H     3.04441381 +1  -1.99108720 +1   1.47331874 +1
  N     3.54254360 +1   0.93087755 +1  -0.23578489 +1
  O     4.73738458 +1   1.07219788 +1  -0.03253112 +1
  O     2.95901744 +1   1.47956721 +1  -1.15141827 +1
  O     2.93195683 +1   3.06632077 +1   6.45781444 +1
  H     3.23278834 +1   2.27659776 +1   6.75112826 +1
  N    -1.52429138 +1   2.39880580 +1  -0.02955071 +1
  O    -2.70108360 +1   2.37640638 +1  -0.35676897 +1
  O    -0.95515200 +1   3.42986897 +1   0.29670068 +1
  H     2.74212205 +1   1.37492097 +1   3.31722899 +1
  H     3.25558993 +1   1.95790314 +1   4.62528090 +1
  O     3.54342099 +1   1.45355220 +1   3.84186358 +1

